services:
  acm:
    build: .
    ports:
      - '8000:8000'
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=debug
      - ACM_AUTO_SEED=1
      - ACM_AUTO_STEP=0
      - ACM_AUTO_STEP_INTERVAL=2
      - ACM_AUTO_STEP_SIZE=100
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
